import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fakr, FakrWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force SSL is disabled — SSL termination is handled externally (e.g. reverse proxy).
# config :fakr, FakrWeb.Endpoint,
#   force_ssl: [
#     rewrite_on: [:x_forwarded_proto],
#     exclude: [
#       hosts: ["localhost", "127.0.0.1"]
#     ]
#   ]

# Swoosh mail adapter is configured at runtime via MAIL_ADAPTER env var.
# See config/runtime.exs for details.

# Disable dev routes (LiveDashboard) in production
config :fakr, dev_routes: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
